### ISSUE TITLE
TTransportException from our platform

### ISSUE THREAD

**Issue by starlight60** [hector-client/hector#108]
Hi..

I have a big problem.

After my cassandra and application(platform) start, running on good condition.
but four or five days later, my application has the problem from random TTransportException. (see below)

Case 1
[WARN]     : Skip-host failed      [FailoverOperator.java.operate():104]
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:333)
        at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:195)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
        at java.net.Socket.connect(Socket.java:529)
        at java.net.Socket.connect(Socket.java:478)
        at org.apache.thrift.transport.TSocket.open(TSocket.java:180)

Case 2
[WARN]     : org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection timed out

Case 3
[WARN]     : Got a HectorTException from 211.113.17.131:45201. Num of retries: 0; message: org.apache.thrift.transport.TTransportException: Cannot write to null outputStream; cause: org.apache.thrift.transport.TTransportException: Cannot write to null outputStream (thread=TP-Processor544)  [FailoverOperator.java.operateSingleIteration():217]

this is our condition.

Cassandra version : 0.6.3
Hector version : 0.6.0-18
Cassandra cluster : has 2 node
Client Server (HTTP Server) : has 3
Traffic : 
      RESPONSE-STAGE : 532062 per hour
      ROW-READ-STAGE  : 492055 per hour
Cassandra configuration : 
    <ReplicationFactor>2</ReplicationFactor>
    <ReplicaPlacementStrategy>org.apache.cassandra.locator.RackUnawareStrategy</ReplicaPlacementStrategy>
Consistency Level : QUOTUM

I heared about this the epic race condition problem. and this problem will be fixed on 0.7.x.
but We cannot upgrade right now. (because 0.7.x is not stable, and upgrade issue)

Thank you for your corporating.^^

**Comment by wz2326** [comment]
It is not answer！
