### ISSUE TITLE
me.prettyprint.hector.api.exceptions.HectorTransportException: Unable to open transport to (192.168.1.6):9160

### ISSUE THREAD

**Issue by salihkardan** [hector-client/hector#645]
Hi all,

I am trying to insert flume logs into cassandra, and while connecting to cassandra from flume-node I am getting this error. 
# error

2013-12-09 19:38:39,888 (lifecycleSupervisor-1-3) [WARN - me.prettyprint.cassandra.connection.HConnectionManager.operateWithFailover(HConnectionManager.java:307)] Exception: 
me.prettyprint.hector.api.exceptions.HectorTransportException: Unable to open transport to salih(192.168.1.6):9160 , java.net.ConnectException: Connection refused
    at me.prettyprint.cassandra.connection.client.HThriftClient.open(HThriftClient.java:176)
    at me.prettyprint.cassandra.connection.client.HThriftClient.open(HThriftClient.java:38)
    at me.prettyprint.cassandra.connection.ConcurrentHClientPool.createClient(ConcurrentHClientPool.java:146)
    at me.prettyprint.cassandra.connection.ConcurrentHClientPool.borrowClient(ConcurrentHClientPool.java:78)
    at me.prettyprint.cassandra.connection.HConnectionManager.operateWithFailover(HConnectionManager.java:250)
    at me.prettyprint.cassandra.service.AbstractCluster.describeKeyspaces(AbstractCluster.java:136)
    at me.prettyprint.cassandra.connection.NodeAutoDiscoverService.discoverNodes(NodeAutoDiscoverService.java:97)
    at me.prettyprint.cassandra.connection.NodeAutoDiscoverService.doAddNodes(NodeAutoDiscoverService.java:68)
    at me.prettyprint.cassandra.connection.HConnectionManager.doAddNodes(HConnectionManager.java:94)
    at me.prettyprint.cassandra.service.ThriftCluster.onStartup(ThriftCluster.java:175)
    at me.prettyprint.hector.api.factory.HFactory.createCluster(HFactory.java:200)
    at com.btoddb.flume.sinks.cassandra.CassandraSinkRepository.init(CassandraSinkRepository.java:107)
    at com.btoddb.flume.sinks.cassandra.CassandraSink.start(CassandraSink.java:95)
    at org.apache.flume.sink.DefaultSinkProcessor.start(DefaultSinkProcessor.java:46)
    at org.apache.flume.SinkRunner.start(SinkRunner.java:79)
    at org.apache.flume.lifecycle.LifecycleSupervisor$MonitorRunnable.run(LifecycleSupervisor.java:251)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
    at org.apache.thrift.transport.TSocket.open(TSocket.java:183)
    at org.apache.thrift.transport.TFramedTransport.open(TFramedTransport.java:81)
    at me.prettyprint.cassandra.connection.client.HThriftClient.open(HThriftClient.java:170)
    ... 23 more
Caused by: java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at org.apache.thrift.transport.TSocket.open(TSocket.java:178)
    ... 25 more

**Comment by chandruhigy** [comment]
Thanks salihkardan this worked
