### ISSUE TITLE
default validator comparator type on hector clients: "cannot parse 'SomeColumn' as hex bytes"

### ISSUE THREAD

**Issue by krishna81m** [hector-client/hector#674]
I am testing if we can upgrade our cassandra 1.2.13 to 1.2.19 and spun up a single instance and populated data from 1.2 without any problem, everything works, even from a IDE client on thrift:9160 port is able to run this query. 

However, hector throws an exception, although we do read by passing key, value, name serializer as string, but shouldn't there be a way to specify the default validator, comparator also as UTF8?
CqlQuery<String, String, String> cqlQuery = new CqlQuery<String, String, String>(instance.getMasterKeyspace(),STR_SERIALIZER,STR_SERIALIZER,STR_SERIALIZER);

The fix was to explicitly create the tables
WITH COMPACT STORAGE

to get the default validator, comparator types to UTF8Type.
http://www.planetcassandra.org/blog/datastax-developer-blog-a-thrift-to-cql3-upgrade-guide/

```
Caused by: InvalidRequestException(why:cannot parse 'SomeColumn' as hex bytes)
    at org.apache.cassandra.thrift.Cassandra$execute_cql_query_result.read(Cassandra.java:36625)
    at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
    at org.apache.cassandra.thrift.Cassandra$Client.recv_execute_cql_query(Cassandra.java:1525)
    at org.apache.cassandra.thrift.Cassandra$Client.execute_cql_query(Cassandra.java:1511)
    at me.prettyprint.cassandra.model.CqlQuery$1.execute(CqlQuery.java:118)
    ... 88 more

```

**Comment by zznate** [comment]
I appreciate the questions and update, but please see this section of the
README:
https://github.com/hector-client/hector/blob/master/README#L3-L10

This project is no longer active.

**Comment by krishna81m** [comment]
Uh oh, we do use both, we have quite a bit of code still using hector, don't think that is an easy migration :)

**Comment by Ursula** [comment]
We do too.  When upgrading to Cassandra 2.0  I was able to build and use the 2.0 Hector version successfully in production.   We are finding that Hector's performance for bulk loading of data far exceeds  the performance of the CQL Driver.  However, as you found you will need to use compact storage  and define tables using the cli using the old style.  For example if you need to have composite keys.  e.g. 

CREATE COLUMN FAMILY ORDER_LINE WITH COLUMN_TYPE = 'Standard' AND COMPARATOR = 'UTF8Type' AND key_validation_class = 'UTF8Type' 
  AND default_validation_class = 'UTF8Type'
  AND caching = 'NONE'
  AND column_metadata = [
{column_name: orderNumber , validation_class: UTF8Type, index_type: KEYS}
{column_name: lineNumber  , validation_class: UTF8Type, index_type: KEYS}
{column_name:   price       , validation_class: UTF8Type}
{column_name:   itemTax         , validation_class: UTF8Type}
{column_name:   itemDesc        , validation_class: UTF8Type}
];
